### ISSUE TITLE
Question: How to show all Records at in Table? How to set show entries "All" and also please add new option to export as 'PDF' or Print

### ISSUE THREAD

**Issue by Rajasekhar1989** [uwla/vue-data-table#47]

**Comment by AndreSouzaAbreu** [comment]
To show all records in the table at once, just use the `perPageSizes` settings.
For example, set `perPageSizes` to `[ 10000 ]`. Since `10000` is a large value,
all entries will be shown at once. You can also set `showPerPage` to `false` to
hide the select menu.


It is not possible to export data to PDF. VueDataTable uses another lib to
export JSON data to other formats, but this lib doesn't export to PDF. If you
know a better lib with more options, please let me know that I will consider
replace the current lib with a new one.

**Comment by Rajasekhar1989** [comment]
Thanks.....
but In your README.md file, you said like... It was inspired by [DataTable jQuery Plugin](https://datatables.net/). so i think all the features are available here only..... https://datatables.net/. we used this plugin previously its having all. but we are upgraded our application to VUEJs. 

And also HTML Image support also available on the above plugin, This question was asked you our colleague only. 

Please try to add those above features, its very use full for all.

**Comment by uwla** [comment]
I realized these features are wanted.
We should have a "show all" and a "export as pdf" option.

These will be added in the next couple of weeks.

**Comment by uwla** [comment]
@Rajasekhar1989 the "All" entries options was enabled and will be available soon in the next release. I'll plan to add export as PDF afterwards. Thanks for using the plugin
